/**
 * Deterministic mirror of the backend score catalog
 * (`backend/agents/orchestras.py::SCORES`).
 *
 * This powers the dashboard without a live backend round-trip, exactly like
 * `src/lib/dashboard/mock.ts`. To swap in the FastAPI conductor, point the
 * client (`./api.ts`) at `/api/orchestras` — the panels keep working.
 *
 * Keep this in lockstep with the Python catalog.
 */

import type { ScoreDef } from './types';

export const ORCHESTRA_SCORES: ScoreDef[] = [
  {
    id: 'morning_executive',
    name: 'Morning Executive Overture',
    summary:
      'The daily executive open: pull mesh telemetry, compose the ops brief, run a governance risk pass, and stamp the audit trail.',
    advisoryOnly: true,
    movementCount: 4,
    sections: ['AuditBeacon', 'Cyborg', 'Stephanie'],
    gatedMovements: 0,
    movements: [
      {
        id: 'telemetry',
        title: 'System telemetry',
        section: 'Stephanie',
        eventType: 'get_telemetry',
        description: 'Snapshot pipeline + agent health for the executive view.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'ops_brief',
        title: 'Compose ops brief',
        section: 'Stephanie',
        eventType: 'generate_ops_brief',
        description: 'Gather stale leads, deposits, blockers, at-risk jobs, receivables.',
        critical: true,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'risk_pass',
        title: 'Governance risk pass',
        section: 'Cyborg',
        eventType: 'assess_risk',
        description: 'Score cross-system risk before it reaches the owner.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'audit',
        title: 'Stamp audit trail',
        section: 'AuditBeacon',
        eventType: 'record_event',
        description: 'Immutable record that the briefing ran.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
    ],
  },
  {
    id: 'intake_to_estimate',
    name: 'New Demand Intake',
    summary:
      'Route a fresh lead, pre-check zoning and permit risk for its property, and record the intake — all advisory, nothing executed.',
    advisoryOnly: true,
    movementCount: 4,
    sections: ['AuditBeacon', 'PermitStream', 'Stephanie'],
    gatedMovements: 0,
    movements: [
      {
        id: 'route_intake',
        title: 'Route intake',
        section: 'Stephanie',
        eventType: 'route_intake',
        description: 'Decide pipeline stage and priority for the lead.',
        critical: true,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'zoning',
        title: 'Zoning pre-check',
        section: 'PermitStream',
        eventType: 'check_zoning_compliance',
        description: 'Advisory zoning compatibility for the property address.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'permit_risk',
        title: 'Permit risk',
        section: 'PermitStream',
        eventType: 'assess_permit_risk',
        description: 'Score likely permit friction for the AHJ.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'audit',
        title: 'Record intake',
        section: 'AuditBeacon',
        eventType: 'record_event',
        description: 'Immutable record of the intake decision.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
    ],
  },
  {
    id: 'permit_sweep',
    name: 'Permit Risk Sweep',
    summary:
      'Find permit blockers, forecast approval timelines, score the risk, and log the sweep for the compliance record.',
    advisoryOnly: true,
    movementCount: 4,
    sections: ['AuditBeacon', 'Cyborg', 'PermitStream'],
    gatedMovements: 0,
    movements: [
      {
        id: 'blockers',
        title: 'Detect blockers',
        section: 'PermitStream',
        eventType: 'detect_permit_blockers',
        description: 'Surface projects stuck in permit review.',
        critical: true,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'timeline',
        title: 'Forecast timelines',
        section: 'PermitStream',
        eventType: 'forecast_approval_timeline',
        description: 'Project approval cycle time per municipality.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'risk',
        title: 'Score risk',
        section: 'Cyborg',
        eventType: 'assess_risk',
        description: 'Roll permit exposure into the governance risk view.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'audit',
        title: 'Log sweep',
        section: 'AuditBeacon',
        eventType: 'record_event',
        description: 'Immutable record of the permit sweep.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
    ],
  },
  {
    id: 'deposit_to_production',
    name: 'Deposit-to-Production Handoff',
    summary:
      'Coordinate the move from signed deposit into production. The actual payment release is human-gated and demonstrates the freeze: the conductor stages it for approval rather than disbursing.',
    advisoryOnly: true,
    movementCount: 4,
    sections: ['AuditBeacon', 'GCagent', 'Stephanie'],
    gatedMovements: 1,
    movements: [
      {
        id: 'route',
        title: 'Route handoff',
        section: 'Stephanie',
        eventType: 'route_task',
        description: 'Coordinate the deposit-to-production handoff.',
        critical: true,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'payment',
        title: 'Release deposit funds',
        section: 'Stephanie',
        eventType: 'autonomous_payment_disbursement',
        description: 'Disburse mobilization funds (human-gated — staged, not executed).',
        critical: false,
        gated: true,
        gateReason: 'financial_risk',
        humanAlternative: 'Stage payment for human approval via Stripe dashboard',
      },
      {
        id: 'job_health',
        title: 'Assess job health',
        section: 'GCagent',
        eventType: 'assess_job_health',
        description: 'Baseline production health once mobilized.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
      {
        id: 'audit',
        title: 'Record handoff',
        section: 'AuditBeacon',
        eventType: 'record_event',
        description: 'Immutable record of the handoff coordination.',
        critical: false,
        gated: false,
        gateReason: null,
        humanAlternative: null,
      },
    ],
  },
];

export const getScore = (id: string): ScoreDef | undefined =>
  ORCHESTRA_SCORES.find((s) => s.id === id);
